on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Run Crashtest Security Scan
    steps:
    - name: Crashtest Security Action Step
      id: crashtest-security
      uses: crashtest-security/crashtest-security-action@v1.0.0
      with:
        crashtest-webhook: '${{ secrets.CRASHTEST_WEBHOOK }}'
        pull-report: 'true'
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v1
      with:
        report_paths: 'report.xml'
        github_token: ${{ secrets.GITHUB_TOKEN }}